<?php

return [
    'Wie hat sich das letzte Deployment angefühlt?',
    'Dieser Sprint in einem GIF?',
    'Was hältst du von unserem Backlog?',
    'Wie sah das letzte Daily aus?',
    'Wie fühlst du dich gerade?',
    'Wie fühlt sich ein Montagmorgen an?',
    'Wie hast du auf den letzten Bugreport reagiert?',
    'Wie sieht unser Team am Freitagnachmittag aus?',
    'Wie lief die letzte Demo?',
    'Was war dein Gesicht, als der Build rot wurde?',
    'Was erwartest du vom nächsten Sprint?',
    'Wie fühlt sich ein Code-Review an?',
    'Wie war deine Woche?',
    'Was denkt die Kaffeemaschine über uns?',
    'Wie hast du dich gefühlt, als die Tests grün wurden?',
    'Wie fühlt sich ein Merge-Konflikt an?',
    'Wie würdest du unser letztes Meeting beschreiben?',
    'Wie fühlt es sich an, ein Ticket zu schließen?',
    'Was hältst du von Schätzungen?',
    'Was war die größte Überraschung im Sprint?',
    'Wie ist das Team mit dem letzten Notfall umgegangen?',
    'Wie sieht Homeoffice heute aus?',
    'Was hältst du von Deadlines?',
    'Wie sieht dein Posteingang aus?',
    'Wie hast du dich in der Planung gefühlt?',
    'Wie sieht unsere Velocity aus?',
    'Wie fühlt sich Pair Programming an?',
    'Wie feierst du ein Release?',
    'Wie fühlt sich ein Produktionsvorfall an?',
    'Wie hast du dich gefühlt, als sich die Anforderungen geändert haben?',
    'Wie sah die letzte Retro aus?',
    'Was hältst du von der Dokumentation?',
    'Wie fühlt es sich an, ein neues Tool zu lernen?',
    'Wie ist dein Energielevel heute?',
    'Wie sieht das Ende des Sprints aus?',
    'Wie fühlst du dich nach dem Mittagessen?',
    'Wie fühlt sich ein langes Meeting an?',
    'Wie hast du dich gefühlt, als der Kunde Ja gesagt hat?',
    'Wie sieht der Team-Chat gerade aus?',
    'Wie fühlt es sich an, alten Code zu refaktorieren?',
    'Was erwartest du vom nächsten Release?',
    'Wie sieht ein perfekter Arbeitstag aus?',
    'Wie war deine Einarbeitung?',
    'Wie sieht deine To-do-Liste aus?',
    'Wie hast du dich gefühlt, als der Server ausgefallen ist?',
    'Wie sieht unser Teamgeist aus?',
    'Wie fühlst du dich, wenn jemand „kurze Frage“ sagt?',
    'Wie fühlt es sich an, auf die Pipeline zu warten?',
    'Was hältst du von den Überraschungen dieser Woche?',
    'Wie fühlt es sich an, eine große Aufgabe abzuschließen?',
    'Was hältst du von unseren Zielen?',
    'Wie fühlt sich ein Deployment am Freitag an?',
    'Wie lief der letzte Workshop?',
    'Wie sieht dein Gehirn gerade aus?',
    'Was hältst du vom nahenden Urlaub?',
    'Wie fühlt sich Backlog-Refinement an?',
    'Wie hast du dich gefühlt, als du den Bug gefunden hast?',
    'Wie sieht unser Daily von außen aus?',
    'Was hältst du davon, etwas Neues auszuprobieren?',
    'Wie sieht Teamarbeit aus?',
    'Wie würdest du diesen Monat zusammenfassen?',
    'Wie fühlt sich ein ruhiger Arbeitstag an?',
];
