<?php

return [
    'How did the last deploy feel?',
    'How was this sprint, in one GIF?',
    'How do you feel about our backlog?',
    'What did the last standup look like?',
    'How do you feel right now?',
    'What does Monday morning feel like?',
    'How did you react to the last bug report?',
    'What does our team look like on a Friday afternoon?',
    'How did the last demo go?',
    'What was your face when the build turned red?',
    'How do you feel about the next sprint?',
    'What does a code review feel like?',
    'How was your week?',
    'What does our coffee machine think of us?',
    'How did you feel when the tests passed?',
    'What does a merge conflict feel like?',
    'How would you describe our last meeting?',
    'What does it feel like to close a ticket?',
    'How do you feel about estimates?',
    'What was the biggest surprise of the sprint?',
    'How did the team handle the last emergency?',
    'What does working from home look like today?',
    'How do you feel about deadlines?',
    'What does your inbox look like?',
    'How did you feel during the planning?',
    'What does our velocity look like?',
    'What does pairing with a teammate feel like?',
    'How do you celebrate a release?',
    'What does a production incident feel like?',
    'How did you feel when the requirements changed?',
    'What did the last retro look like?',
    'How do you feel about the documentation?',
    'What does learning a new tool feel like?',
    'How is your energy level today?',
    'What does the end of the sprint look like?',
    'How do you feel after lunch?',
    'What does a long meeting feel like?',
    'How did you feel when the customer said yes?',
    'What does the team chat look like right now?',
    'What does refactoring old code feel like?',
    'How do you feel about the next release?',
    'What does a perfect workday look like?',
    'How did the onboarding feel?',
    'What does your to-do list look like?',
    'How did you feel when the server went down?',
    'What does our team spirit look like?',
    'How do you feel when someone says "quick question"?',
    'What does waiting for the pipeline feel like?',
    "How did you feel about this week's surprises?",
    'What does finishing a big task feel like?',
    'How do you feel about our goals?',
    'What does a Friday deploy feel like?',
    'How did the last workshop go?',
    'What does your brain look like right now?',
    'How do you feel about the holidays coming?',
    'What does backlog refinement feel like?',
    'How did you feel when you found the bug?',
    'What does our daily look like from the outside?',
    'How do you feel about trying something new?',
    'What does teamwork look like?',
    'How would you sum up this month?',
    'What does a quiet day at work feel like?',
];
