<?php

return [
    '¿Cómo fue el último despliegue?',
    '¿Este sprint, en un GIF?',
    '¿Qué opinas de nuestro backlog?',
    '¿Cómo fue la última daily?',
    '¿Cómo te sientes ahora mismo?',
    '¿Cómo se siente un lunes por la mañana?',
    '¿Cómo reaccionaste al último informe de error?',
    '¿Cómo es nuestro equipo un viernes por la tarde?',
    '¿Cómo fue la última demo?',
    '¿Qué cara pusiste cuando la build se puso en rojo?',
    '¿Qué esperas del próximo sprint?',
    '¿Qué se siente en una revisión de código?',
    '¿Qué tal tu semana?',
    '¿Qué piensa la cafetera de nosotros?',
    '¿Qué sentiste cuando pasaron los tests?',
    '¿Qué se siente con un conflicto de fusión?',
    '¿Cómo describirías nuestra última reunión?',
    '¿Qué se siente al cerrar un ticket?',
    '¿Qué opinas de las estimaciones?',
    '¿Cuál fue la mayor sorpresa del sprint?',
    '¿Cómo manejó el equipo la última emergencia?',
    '¿Cómo es hoy trabajar desde casa?',
    '¿Qué opinas de las fechas límite?',
    '¿Cómo está tu bandeja de entrada?',
    '¿Cómo te sentiste durante la planificación?',
    '¿Cómo se ve nuestra velocidad?',
    '¿Qué se siente al programar en pareja?',
    '¿Cómo celebras un lanzamiento?',
    '¿Qué se siente con un incidente en producción?',
    '¿Qué sentiste cuando cambiaron los requisitos?',
    '¿Cómo fue la última retro?',
    '¿Qué opinas de la documentación?',
    '¿Qué se siente al aprender una herramienta nueva?',
    '¿Cómo está tu nivel de energía hoy?',
    '¿Cómo se ve el final del sprint?',
    '¿Cómo te sientes después de comer?',
    '¿Qué se siente en una reunión larga?',
    '¿Qué sentiste cuando el cliente dijo que sí?',
    '¿Cómo está ahora mismo el chat del equipo?',
    '¿Qué se siente al refactorizar código antiguo?',
    '¿Qué esperas de la próxima versión?',
    '¿Cómo sería un día de trabajo perfecto?',
    '¿Cómo fue tu incorporación?',
    '¿Cómo está tu lista de tareas?',
    '¿Qué sentiste cuando se cayó el servidor?',
    '¿Cómo es nuestro espíritu de equipo?',
    '¿Qué sientes cuando alguien dice «una pregunta rápida»?',
    '¿Qué se siente al esperar al pipeline?',
    '¿Qué te parecieron las sorpresas de esta semana?',
    '¿Qué se siente al terminar una tarea grande?',
    '¿Qué opinas de nuestros objetivos?',
    '¿Qué se siente al desplegar un viernes?',
    '¿Cómo fue el último taller?',
    '¿Cómo está tu cerebro ahora mismo?',
    '¿Qué opinas de las vacaciones que se acercan?',
    '¿Qué se siente al refinar el backlog?',
    '¿Qué sentiste al encontrar el error?',
    '¿Cómo se ve nuestra daily desde fuera?',
    '¿Qué opinas de probar algo nuevo?',
    '¿Cómo es el trabajo en equipo?',
    '¿Cómo resumirías este mes?',
    '¿Qué se siente en un día tranquilo de trabajo?',
];
