<?php

return [
    "Comment s'est passé le dernier déploiement ?",
    'Ce sprint, en un GIF ?',
    'Que pensez-vous de notre backlog ?',
    'À quoi ressemblait le dernier stand-up ?',
    'Comment vous sentez-vous en ce moment ?',
    'À quoi ressemble le lundi matin ?',
    'Comment avez-vous réagi au dernier rapport de bug ?',
    "À quoi ressemble l'équipe le vendredi après-midi ?",
    "Comment s'est passée la dernière démo ?",
    'Quelle tête avez-vous faite quand le build est passé au rouge ?',
    'Comment voyez-vous le prochain sprint ?',
    "Qu'est-ce que ça fait, une revue de code ?",
    "Comment s'est passée votre semaine ?",
    'Que pense la machine à café de nous ?',
    "Qu'avez-vous ressenti quand les tests sont passés ?",
    "Qu'est-ce que ça fait, un conflit de fusion ?",
    'Comment décririez-vous notre dernière réunion ?',
    "Qu'est-ce que ça fait de fermer un ticket ?",
    'Que pensez-vous des estimations ?',
    'Quelle a été la plus grande surprise du sprint ?',
    "Comment l'équipe a-t-elle géré la dernière urgence ?",
    "À quoi ressemble le télétravail aujourd'hui ?",
    'Que pensez-vous des échéances ?',
    'À quoi ressemble votre boîte mail ?',
    'Comment vous êtes-vous senti pendant la planification ?',
    'À quoi ressemble notre vélocité ?',
    "Qu'est-ce que ça fait de travailler en binôme ?",
    'Comment fêtez-vous une mise en production ?',
    "Qu'est-ce que ça fait, un incident en production ?",
    "Qu'avez-vous ressenti quand le besoin a changé ?",
    'À quoi ressemblait la dernière rétro ?',
    'Que pensez-vous de la documentation ?',
    "Qu'est-ce que ça fait d'apprendre un nouvel outil ?",
    "Quel est votre niveau d'énergie aujourd'hui ?",
    'À quoi ressemble la fin du sprint ?',
    'Comment vous sentez-vous après le déjeuner ?',
    "Qu'est-ce que ça fait, une longue réunion ?",
    "Qu'avez-vous ressenti quand le client a dit oui ?",
    "À quoi ressemble le chat de l'équipe en ce moment ?",
    "Qu'est-ce que ça fait de refactoriser du vieux code ?",
    'Comment voyez-vous la prochaine version ?',
    'À quoi ressemble une journée de travail parfaite ?',
    "Comment s'est passée votre intégration ?",
    'À quoi ressemble votre liste de tâches ?',
    "Qu'avez-vous ressenti quand le serveur est tombé ?",
    "À quoi ressemble notre esprit d'équipe ?",
    "Que ressentez-vous quand quelqu'un dit « petite question » ?",
    "Qu'est-ce que ça fait d'attendre le pipeline ?",
    "Qu'avez-vous pensé des surprises de la semaine ?",
    "Qu'est-ce que ça fait de terminer une grosse tâche ?",
    'Que pensez-vous de nos objectifs ?',
    "Qu'est-ce que ça fait, un déploiement le vendredi ?",
    "Comment s'est passé le dernier atelier ?",
    'À quoi ressemble votre cerveau en ce moment ?',
    'Que pensez-vous des vacances qui approchent ?',
    "Qu'est-ce que ça fait, l'affinage du backlog ?",
    "Qu'avez-vous ressenti en trouvant le bug ?",
    "À quoi ressemble notre daily vu de l'extérieur ?",
    "Que pensez-vous d'essayer quelque chose de nouveau ?",
    "À quoi ressemble le travail d'équipe ?",
    'Comment résumeriez-vous ce mois-ci ?',
    "Qu'est-ce que ça fait, une journée calme au travail ?",
];
