<?php

return [
    "Comment s'est passé le dernier déploiement ?",
    'Ce sprint, en un GIF ?',
    'Que penses-tu de notre backlog ?',
    'À quoi ressemblait le dernier stand-up ?',
    'Comment te sens-tu en ce moment ?',
    'À quoi ressemble le lundi matin ?',
    'Comment as-tu réagi au dernier rapport de bug ?',
    "À quoi ressemble l'équipe le vendredi après-midi ?",
    "Comment s'est passée la dernière démo ?",
    'Quelle tête as-tu faite quand le build est passé au rouge ?',
    'Comment vois-tu le prochain sprint ?',
    "Qu'est-ce que ça fait, une revue de code ?",
    "Comment s'est passée ta semaine ?",
    'Que pense la machine à café de nous ?',
    "Qu'as-tu ressenti quand les tests sont passés ?",
    "Qu'est-ce que ça fait, un conflit de fusion ?",
    'Comment décrirais-tu notre dernière réunion ?',
    "Qu'est-ce que ça fait de fermer un ticket ?",
    'Que penses-tu des estimations ?',
    'Quelle a été la plus grande surprise du sprint ?',
    "Comment l'équipe a-t-elle géré la dernière urgence ?",
    "À quoi ressemble le télétravail aujourd'hui ?",
    'Que penses-tu des échéances ?',
    'À quoi ressemble ta boîte mail ?',
    "Comment t'es-tu senti pendant la planification ?",
    'À quoi ressemble notre vélocité ?',
    "Qu'est-ce que ça fait de travailler en binôme ?",
    'Comment fêtes-tu une mise en production ?',
    "Qu'est-ce que ça fait, un incident en production ?",
    "Qu'as-tu ressenti quand le besoin a changé ?",
    'À quoi ressemblait la dernière rétro ?',
    'Que penses-tu de la documentation ?',
    "Qu'est-ce que ça fait d'apprendre un nouvel outil ?",
    "Quel est ton niveau d'énergie aujourd'hui ?",
    'À quoi ressemble la fin du sprint ?',
    'Comment te sens-tu après le déjeuner ?',
    "Qu'est-ce que ça fait, une longue réunion ?",
    "Qu'as-tu ressenti quand le client a dit oui ?",
    "À quoi ressemble le chat de l'équipe en ce moment ?",
    "Qu'est-ce que ça fait de refactoriser du vieux code ?",
    'Comment vois-tu la prochaine version ?',
    'À quoi ressemble une journée de travail parfaite ?',
    "Comment s'est passée ton intégration ?",
    'À quoi ressemble ta liste de tâches ?',
    "Qu'as-tu ressenti quand le serveur est tombé ?",
    "À quoi ressemble notre esprit d'équipe ?",
    "Que ressens-tu quand quelqu'un dit « petite question » ?",
    "Qu'est-ce que ça fait d'attendre le pipeline ?",
    "Qu'as-tu pensé des surprises de la semaine ?",
    "Qu'est-ce que ça fait de terminer une grosse tâche ?",
    'Que penses-tu de nos objectifs ?',
    "Qu'est-ce que ça fait, un déploiement le vendredi ?",
    "Comment s'est passé le dernier atelier ?",
    'À quoi ressemble ton cerveau en ce moment ?',
    'Que penses-tu des vacances qui approchent ?',
    "Qu'est-ce que ça fait, l'affinage du backlog ?",
    "Qu'as-tu ressenti en trouvant le bug ?",
    "À quoi ressemble notre daily vu de l'extérieur ?",
    "Que penses-tu d'essayer quelque chose de nouveau ?",
    "À quoi ressemble le travail d'équipe ?",
    'Comment résumerais-tu ce mois-ci ?',
    "Qu'est-ce que ça fait, une journée calme au travail ?",
];
