#!/bin/sh
server_name="${SERVER_NAME:-:8000}"
server_name="${server_name#http://}"
server_name="${server_name#https://}"

case "$server_name" in
    :*)
        exec curl -fsS -o /dev/null "http://127.0.0.1${server_name}/up"
        ;;
    *)
        exec curl -fsSk -o /dev/null --resolve "${server_name}:8443:127.0.0.1" "https://${server_name}:8443/up"
        ;;
esac
