<?php

return [
    'Was war dein allererster Job?',
    'Ohne welche App könntest du nicht leben?',
    'Was ist dein Lieblingssnack bei der Arbeit?',
    'Bei welchem Lied kennst du den ganzen Text?',
    'Was wolltest du als Kind werden?',
    'Was war die schönste Reise, die du je gemacht hast?',
    'Welche Fähigkeit möchtest du dieses Jahr lernen?',
    'Was ist dein Lieblingsbrettspiel?',
    'Welchen Film kannst du immer wieder schauen?',
    'Was ist das seltsamste Essen, das du probiert hast?',
    'Deine Morgenroutine in drei Worten?',
    'Welche fiktive Figur würdest du gern treffen?',
    'Was war dein erster Computer oder dein erstes Handy?',
    'Welchen Sport hast du in der Schule gemacht?',
    'Was ist der beste Rat, den du je bekommen hast?',
    'Was ist dein Lieblingswort in einer anderen Sprache?',
    'Welches Hobby würde deine Kollegen überraschen?',
    'Was ist dein Karaoke-Lied?',
    'Von wo würdest du gern einen Monat remote arbeiten?',
    'Welches Buch hat dir zuletzt gefallen?',
    'Welches Tier wärst du, und warum?',
    'Was ist deine Lieblingsjahreszeit?',
    'Was ist das beste Geschenk, das du je bekommen hast?',
    'Welche Erfindung würdest du aus der Welt schaffen?',
    'Was ist dein verstecktes Talent?',
    'Was kochst du, wenn du keine Zeit hast?',
    'Welchen Ort aus deiner Kindheit vermisst du?',
    'Was ist dein liebstes Tastenkürzel?',
    'Was würdest du mit einer Stunde mehr am Tag machen?',
    'Welches Werkzeug sollte es bei der Arbeit geben?',
    'Was ist der lustigste Bug, den du gesehen hast?',
    'Welchem Podcast oder Kanal folgst du?',
    'Wie schaltest du am liebsten ab?',
    'In welchem Jahrzehnt würdest du gern leben?',
    'Welche Stadt hat dir von allen am besten gefallen?',
    'Was war dein erstes Konzert?',
    'Welche Superkraft würde dir bei der Arbeit helfen?',
    'Was magst du an diesem Team am meisten?',
    'Was war dein bestes Essen in diesem Jahr?',
    'Welches Spiel hast du als Kind am meisten gespielt?',
    'Worüber hast du deine Meinung geändert?',
    'Was ist deine Lieblingspflanze oder -blume?',
    'Welchen Beruf würdest du einen Tag lang ausprobieren?',
    'Was war das Nützlichste, das du letztes Jahr gelernt hast?',
    'Welches Emoji benutzt du am meisten?',
    'Was ist dein Lieblingsgeräusch?',
    'Welche Sprache würdest du gern sprechen?',
    'Wie sieht dein perfektes Wochenende aus?',
    'Welche Kleinigkeit hat dich diese Woche glücklich gemacht?',
    'Was ist das älteste Ding, das du noch jeden Tag benutzt?',
    'Mit welcher historischen Person würdest du gern zu Mittag essen?',
    'Was ist dein Lieblingsgetränk am Freitag?',
    'Welchen Film würdest du neu drehen?',
    'Was machst du am liebsten draußen?',
    'Was ist der beste Name für ein Haustier?',
    'Welche Gewohnheit möchtest du anfangen?',
    'Was ist die schönste Aussicht, die du je gesehen hast?',
    'Welches Meeting-Ritual würdest du erfinden?',
    'Wie würde deine Autobiografie heißen?',
    'Was hast du zuletzt gefeiert?',
];
