<?php

return [
    'What was your very first job?',
    'Which app could you not live without?',
    'What is your favourite snack at work?',
    'Which song do you know all the words to?',
    'What did you want to be as a child?',
    'What is the best trip you have ever taken?',
    'Which skill would you like to learn this year?',
    'What is your favourite board game?',
    'Which film can you watch again and again?',
    'What is the strangest food you have tasted?',
    'What is your morning routine in three words?',
    'Which fictional character would you like to meet?',
    'What was your first computer or phone?',
    'Which sport did you play at school?',
    'What is the best advice you were given?',
    'What is your favourite word in another language?',
    'Which hobby would surprise your colleagues?',
    'What is your go-to karaoke song?',
    'Where would you like to work remotely for a month?',
    'What is the last book you enjoyed?',
    'Which animal would you be, and why?',
    'What is your favourite season?',
    'What is the best gift you ever received?',
    'Which invention would you remove from the world?',
    'What is your hidden talent?',
    'What do you cook when you have no time?',
    'Which place from your childhood do you miss?',
    'What is your favourite keyboard shortcut?',
    'What would you do with an extra hour every day?',
    'Which tool do you wish existed at work?',
    'What is the funniest bug you have seen?',
    'Which podcast or channel do you follow?',
    'What is your favourite way to switch off?',
    'Which decade would you like to live in?',
    'What is your favourite city you have visited?',
    'What was your first concert?',
    'Which superpower would help you at work?',
    'What is your favourite thing about this team?',
    'What is the best meal you have had this year?',
    'Which game did you play the most as a child?',
    'What is something you have changed your mind about?',
    'What is your favourite plant or flower?',
    'Which job would you try for one day?',
    'What is the most useful thing you learned last year?',
    'Which emoji do you use the most?',
    'What is your favourite sound?',
    'Which language would you like to speak?',
    'What is your perfect weekend?',
    'Which small thing made you happy this week?',
    'What is the oldest thing you still use every day?',
    'Which historical figure would you like to have lunch with?',
    'What is your favourite drink on a Friday?',
    'Which film would you remake?',
    'What is your favourite thing to do outdoors?',
    'What is the best name for a pet?',
    'Which habit would you like to start?',
    'What is the most beautiful view you have seen?',
    'Which meeting ritual would you invent?',
    'What would your autobiography be called?',
    'What did you celebrate most recently?',
];
