<?php

return [
    '¿Cuál fue tu primer trabajo?',
    '¿Sin qué app no podrías vivir?',
    '¿Cuál es tu tentempié favorito en el trabajo?',
    '¿De qué canción te sabes toda la letra?',
    '¿Qué querías ser de pequeño o pequeña?',
    '¿Cuál es el mejor viaje que has hecho?',
    '¿Qué habilidad te gustaría aprender este año?',
    '¿Cuál es tu juego de mesa favorito?',
    '¿Qué película puedes ver una y otra vez?',
    '¿Cuál es la comida más rara que has probado?',
    '¿Tu rutina de la mañana en tres palabras?',
    '¿Qué personaje de ficción te gustaría conocer?',
    '¿Cuál fue tu primer ordenador o teléfono?',
    '¿Qué deporte practicabas en el colegio?',
    '¿Cuál es el mejor consejo que te han dado?',
    '¿Cuál es tu palabra favorita en otro idioma?',
    '¿Qué afición sorprendería a tus compañeros?',
    '¿Cuál es tu canción de karaoke de siempre?',
    '¿Desde dónde te gustaría teletrabajar durante un mes?',
    '¿Cuál es el último libro que te gustó?',
    '¿Qué animal serías y por qué?',
    '¿Cuál es tu estación del año favorita?',
    '¿Cuál es el mejor regalo que has recibido?',
    '¿Qué invento quitarías del mundo?',
    '¿Cuál es tu talento oculto?',
    '¿Qué cocinas cuando no tienes tiempo?',
    '¿Qué lugar de tu infancia echas de menos?',
    '¿Cuál es tu atajo de teclado favorito?',
    '¿Qué harías con una hora extra cada día?',
    '¿Qué herramienta te gustaría que existiera en el trabajo?',
    '¿Cuál es el bug más gracioso que has visto?',
    '¿Qué pódcast o canal sigues?',
    '¿Cuál es tu forma favorita de desconectar?',
    '¿En qué década te gustaría vivir?',
    '¿Cuál es tu ciudad favorita de las que has visitado?',
    '¿Cuál fue tu primer concierto?',
    '¿Qué superpoder te ayudaría en el trabajo?',
    '¿Qué es lo que más te gusta de este equipo?',
    '¿Cuál es la mejor comida que has tomado este año?',
    '¿A qué juego jugabas más de pequeño o pequeña?',
    '¿Sobre qué has cambiado de opinión?',
    '¿Cuál es tu planta o flor favorita?',
    '¿Qué trabajo probarías durante un día?',
    '¿Qué es lo más útil que aprendiste el año pasado?',
    '¿Qué emoji usas más?',
    '¿Cuál es tu sonido favorito?',
    '¿Qué idioma te gustaría hablar?',
    '¿Cómo es tu fin de semana perfecto?',
    '¿Qué pequeña cosa te hizo feliz esta semana?',
    '¿Qué es lo más antiguo que todavía usas cada día?',
    '¿Con qué personaje histórico te gustaría comer?',
    '¿Cuál es tu bebida favorita de los viernes?',
    '¿Qué película volverías a rodar?',
    '¿Qué es lo que más te gusta hacer al aire libre?',
    '¿Cuál es el mejor nombre para una mascota?',
    '¿Qué hábito te gustaría empezar?',
    '¿Cuál es la vista más bonita que has visto?',
    '¿Qué ritual de reunión inventarías?',
    '¿Cómo se titularía tu autobiografía?',
    '¿Qué es lo último que celebraste?',
];
