<?php

return [
    'Quel a été ton tout premier job ?',
    'Sans quelle appli ne pourrais-tu pas vivre ?',
    'Quel est ton en-cas préféré au travail ?',
    'De quelle chanson connais-tu toutes les paroles ?',
    'Que voulais-tu faire quand tu étais enfant ?',
    'Quel est le plus beau voyage que tu aies fait ?',
    'Quelle compétence aimerais-tu apprendre cette année ?',
    'Quel est ton jeu de société préféré ?',
    'Quel film peux-tu revoir encore et encore ?',
    'Quel est le plat le plus étrange que tu aies goûté ?',
    'Ta routine du matin en trois mots ?',
    'Quel personnage de fiction aimerais-tu rencontrer ?',
    'Quel a été ton premier ordinateur ou téléphone ?',
    "Quel sport pratiquais-tu à l'école ?",
    "Quel est le meilleur conseil qu'on t'ait donné ?",
    'Quel est ton mot préféré dans une autre langue ?',
    'Quel loisir surprendrait tes collègues ?',
    'Quelle est ta chanson fétiche au karaoké ?',
    'Où aimerais-tu télétravailler pendant un mois ?',
    'Quel est le dernier livre que tu as aimé ?',
    'Quel animal serais-tu, et pourquoi ?',
    'Quelle est ta saison préférée ?',
    'Quel est le plus beau cadeau que tu aies reçu ?',
    'Quelle invention supprimerais-tu du monde ?',
    'Quel est ton talent caché ?',
    "Que cuisines-tu quand tu n'as pas le temps ?",
    'Quel lieu de ton enfance te manque ?',
    'Quel est ton raccourci clavier préféré ?',
    "Que ferais-tu d'une heure de plus chaque jour ?",
    'Quel outil aimerais-tu voir exister au travail ?',
    'Quel est le bug le plus drôle que tu aies vu ?',
    'Quel podcast ou quelle chaîne suis-tu ?',
    'Quelle est ta façon préférée de décrocher ?',
    'À quelle décennie aimerais-tu vivre ?',
    'Quelle est ta ville préférée parmi celles que tu as visitées ?',
    'Quel a été ton premier concert ?',
    "Quel super-pouvoir t'aiderait au travail ?",
    "Qu'est-ce que tu préfères dans cette équipe ?",
    'Quel est le meilleur repas que tu aies fait cette année ?',
    'À quel jeu jouais-tu le plus quand tu étais enfant ?',
    "Sur quoi as-tu changé d'avis ?",
    'Quelle est ta plante ou ta fleur préférée ?',
    'Quel métier aimerais-tu essayer pendant une journée ?',
    "Quelle est la chose la plus utile que tu aies apprise l'an dernier ?",
    'Quel emoji utilises-tu le plus ?',
    'Quel est ton son préféré ?',
    'Quelle langue aimerais-tu parler ?',
    'À quoi ressemble ton week-end parfait ?',
    "Quelle petite chose t'a rendu heureux ou heureuse cette semaine ?",
    "Quel est l'objet le plus ancien que tu utilises encore chaque jour ?",
    'Avec quel personnage historique aimerais-tu déjeuner ?',
    'Quelle est ta boisson préférée le vendredi ?',
    'Quel film aimerais-tu refaire ?',
    "Qu'est-ce que tu préfères faire en plein air ?",
    'Quel est le meilleur nom pour un animal de compagnie ?',
    'Quelle habitude aimerais-tu prendre ?',
    'Quelle est la plus belle vue que tu aies vue ?',
    'Quel rituel de réunion inventerais-tu ?',
    'Quel serait le titre de ton autobiographie ?',
    "Qu'as-tu fêté en dernier ?",
];
