<?php

return [
    ['Kaffee', 'Tee'],
    ['Katze', 'Hund'],
    ['Zug', 'Bus'],
    ['Fluss', 'See'],
    ['Strand', 'Berg'],
    ['Pizza', 'Burger'],
    ['Apfel', 'Birne'],
    ['Regen', 'Schnee'],
    ['Sonne', 'Mond'],
    ['Gitarre', 'Klavier'],
    ['Buch', 'Zeitschrift'],
    ['Stuhl', 'Sofa'],
    ['Fahrrad', 'Roller'],
    ['Kino', 'Theater'],
    ['Hotel', 'Camping'],
    ['Schokolade', 'Karamell'],
    ['Brot', 'Kuchen'],
    ['Wald', 'Dschungel'],
    ['Hai', 'Delfin'],
    ['Fußball', 'Basketball'],
    ['Kugelschreiber', 'Bleistift'],
    ['Telefon', 'Tablet'],
    ['Tastatur', 'Maus'],
    ['Besprechung', 'Workshop'],
    ['E-Mail', 'Brief'],
    ['Koch', 'Bäcker'],
    ['Arzt', 'Krankenpfleger'],
    ['Insel', 'Halbinsel'],
    ['Schmetterling', 'Biene'],
    ['Regenschirm', 'Regenmantel'],
];
