<?php

return [
    ['coffee', 'tea'],
    ['cat', 'dog'],
    ['train', 'bus'],
    ['river', 'lake'],
    ['beach', 'mountain'],
    ['pizza', 'burger'],
    ['apple', 'pear'],
    ['rain', 'snow'],
    ['sun', 'moon'],
    ['guitar', 'piano'],
    ['book', 'magazine'],
    ['chair', 'sofa'],
    ['bike', 'scooter'],
    ['cinema', 'theatre'],
    ['hotel', 'camping'],
    ['chocolate', 'caramel'],
    ['bread', 'cake'],
    ['forest', 'jungle'],
    ['shark', 'dolphin'],
    ['football', 'basketball'],
    ['pen', 'pencil'],
    ['phone', 'tablet'],
    ['keyboard', 'mouse'],
    ['meeting', 'workshop'],
    ['email', 'letter'],
    ['chef', 'baker'],
    ['doctor', 'nurse'],
    ['island', 'peninsula'],
    ['butterfly', 'bee'],
    ['umbrella', 'raincoat'],
];
