<?php

return [
    ['café', 'té'],
    ['gato', 'perro'],
    ['tren', 'autobús'],
    ['río', 'lago'],
    ['playa', 'montaña'],
    ['pizza', 'hamburguesa'],
    ['manzana', 'pera'],
    ['lluvia', 'nieve'],
    ['sol', 'luna'],
    ['guitarra', 'piano'],
    ['libro', 'revista'],
    ['silla', 'sofá'],
    ['bicicleta', 'patinete'],
    ['cine', 'teatro'],
    ['hotel', 'camping'],
    ['chocolate', 'caramelo'],
    ['pan', 'pastel'],
    ['bosque', 'selva'],
    ['tiburón', 'delfín'],
    ['fútbol', 'baloncesto'],
    ['bolígrafo', 'lápiz'],
    ['teléfono', 'tableta'],
    ['teclado', 'ratón'],
    ['reunión', 'taller'],
    ['correo electrónico', 'carta'],
    ['cocinero', 'panadero'],
    ['médico', 'enfermero'],
    ['isla', 'península'],
    ['mariposa', 'abeja'],
    ['paraguas', 'impermeable'],
];
