<?php

return [
    ['café', 'thé'],
    ['chat', 'chien'],
    ['train', 'bus'],
    ['rivière', 'lac'],
    ['plage', 'montagne'],
    ['pizza', 'burger'],
    ['pomme', 'poire'],
    ['pluie', 'neige'],
    ['soleil', 'lune'],
    ['guitare', 'piano'],
    ['livre', 'magazine'],
    ['chaise', 'canapé'],
    ['vélo', 'trottinette'],
    ['cinéma', 'théâtre'],
    ['hôtel', 'camping'],
    ['chocolat', 'caramel'],
    ['pain', 'gâteau'],
    ['forêt', 'jungle'],
    ['requin', 'dauphin'],
    ['football', 'basketball'],
    ['stylo', 'crayon'],
    ['téléphone', 'tablette'],
    ['clavier', 'souris'],
    ['réunion', 'atelier'],
    ['e-mail', 'lettre'],
    ['cuisinier', 'boulanger'],
    ['médecin', 'infirmier'],
    ['île', 'presqu’île'],
    ['papillon', 'abeille'],
    ['parapluie', 'imperméable'],
];
